/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 19 12:00:30 GMT 2018
 */

package org.jsoup.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.CharBuffer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.parser.CharacterReader;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CharacterReader_ESTest extends CharacterReader_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      String string0 = "zd`),NnH";
      CharacterReader characterReader0 = new CharacterReader("zd`),NnH");
      characterReader0.consumeLetterThenDigitSequence();
      String string1 = "F@vH:hjH";
      characterReader0.consumeTo("F@vH:hjH");
      String string2 = "q0yI9jhWk_aE";
      // Undeclared exception!
      try { 
        characterReader0.consumeTo("");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("Must be true");
      characterReader0.consumeTagName();
      characterReader0.consumeLetterThenDigitSequence();
      // Undeclared exception!
      try { 
        characterReader0.rangeEquals(984, 12, "Must be true");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 984
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("Z&L#tC:Bb");
      characterReader0.consumeHexSequence();
      characterReader0.rewindToMark();
      characterReader0.consumeData();
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.pos();
      characterReader0.matchesLetter();
      characterReader0.matchConsume("Z");
      characterReader0.consumeDigitSequence();
      char[] charArray0 = new char[7];
      charArray0[1] = '\u0000';
      charArray0[3] = '.';
      charArray0[2] = 'G';
      charArray0[5] = 'w';
      charArray0[6] = 'L';
      characterReader0.matchesAny(charArray0);
      characterReader0.matches('L');
      characterReader0.toString();
      characterReader0.matches("");
      characterReader0.matchesLetter();
      characterReader0.consumeHexSequence();
      characterReader0.pos();
      characterReader0.matchesDigit();
      characterReader0.consumeHexSequence();
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.mark();
      CharBuffer charBuffer0 = CharBuffer.wrap((CharSequence) "");
      // Undeclared exception!
      try { 
        characterReader0.nextIndexOf(charBuffer0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.consumeTagName();
      characterReader0.unconsume();
      // Undeclared exception!
      try { 
        characterReader0.matchesDigit();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("Y6s'8Byd6j#;l\"wE]");
      characterReader0.consume();
      characterReader0.consumeDigitSequence();
      char[] charArray0 = new char[7];
      characterReader0.consume();
      charArray0[0] = 'Y';
      characterReader0.unconsume();
      charArray0[1] = 'Y';
      charArray0[2] = 'Y';
      characterReader0.consumeToAnySorted(charArray0);
      charArray0[3] = 'Y';
      characterReader0.unconsume();
      characterReader0.consumeLetterThenDigitSequence();
      charArray0[4] = 'Y';
      charArray0[5] = 'Y';
      charArray0[6] = 'Y';
      characterReader0.rewindToMark();
      characterReader0.consumeToAny(charArray0);
      String string0 = "";
      characterReader0.unconsume();
      characterReader0.matchesIgnoreCase("");
      // Undeclared exception!
      try { 
        characterReader0.nextIndexOf('M');
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("Z&L#C:B");
      characterReader0.consumeHexSequence();
      characterReader0.rewindToMark();
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.pos();
      characterReader0.matchesLetter();
      characterReader0.matchConsume("");
      characterReader0.consumeDigitSequence();
      char[] charArray0 = new char[7];
      charArray0[0] = 'V';
      charArray0[1] = 'V';
      charArray0[2] = 'd';
      charArray0[3] = '.';
      charArray0[4] = 'P';
      charArray0[5] = 'w';
      charArray0[6] = 'L';
      characterReader0.rangeEquals('L', 'L', "Z");
      characterReader0.matches('L');
      characterReader0.matches("Z");
      characterReader0.matchesLetter();
      characterReader0.consumeHexSequence();
      characterReader0.pos();
      characterReader0.matchesDigit();
      characterReader0.consumeHexSequence();
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.mark();
      char[] charArray1 = new char[0];
      characterReader0.matchesAny(charArray1);
      characterReader0.matchesDigit();
      characterReader0.consumeAsString();
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("K?C");
      characterReader0.containsIgnoreCase("K?C");
      characterReader0.consume();
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.consumeDigitSequence();
      characterReader0.consumeData();
      characterReader0.consumeTo('+');
      characterReader0.advance();
      // Undeclared exception!
      try { 
        characterReader0.consumeToEnd();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("\":Y/");
      characterReader0.toString();
      characterReader0.containsIgnoreCase("\":Y/");
      // Undeclared exception!
      try { 
        characterReader0.containsIgnoreCase("");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("H,Qt:q?");
      characterReader0.consumeData();
      characterReader0.rewindToMark();
      characterReader0.consumeTo("?");
      characterReader0.nextIndexOf("H,Qt:q?");
      characterReader0.consumeDigitSequence();
      char[] charArray0 = new char[7];
      charArray0[0] = '*';
      charArray0[1] = 'u';
      charArray0[2] = '7';
      charArray0[3] = '~';
      charArray0[4] = '^';
      charArray0[5] = '+';
      charArray0[6] = 'I';
      characterReader0.consumeToAnySorted(charArray0);
      characterReader0.consumeTagName();
      // Undeclared exception!
      try { 
        characterReader0.consumeTo("");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("@6>(8]5}2J");
      characterReader0.matchConsumeIgnoreCase("9lP}qT~7");
      characterReader0.mark();
      characterReader0.consume();
      characterReader0.consumeTagName();
      characterReader0.current();
      characterReader0.isEmpty();
      characterReader0.matches('>');
      characterReader0.nextIndexOf('>');
      characterReader0.rewindToMark();
      characterReader0.consume();
      characterReader0.current();
      characterReader0.consumeTo('>');
      characterReader0.nextIndexOf('?');
      characterReader0.advance();
      char[] charArray0 = new char[4];
      charArray0[2] = '>';
      charArray0[3] = '}';
      characterReader0.consumeToAny(charArray0);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("Z&L#tC:Bb");
      characterReader0.consumeHexSequence();
      characterReader0.rewindToMark();
      characterReader0.consumeData();
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.pos();
      characterReader0.matchConsume("Z");
      characterReader0.consumeDigitSequence();
      char[] charArray0 = new char[7];
      charArray0[0] = 'V';
      charArray0[1] = 'V';
      characterReader0.consumeAsString();
      charArray0[2] = 'd';
      charArray0[3] = '.';
      charArray0[4] = 'P';
      charArray0[5] = 'w';
      charArray0[6] = 'L';
      characterReader0.matchesAny(charArray0);
      characterReader0.matches('L');
      characterReader0.matches("");
      characterReader0.matchesLetter();
      characterReader0.consumeHexSequence();
      characterReader0.pos();
      characterReader0.matchesDigit();
      characterReader0.consumeHexSequence();
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.mark();
      characterReader0.consumeTo("B]?uvSmqFvch\"&Y");
      characterReader0.rangeEquals(3, 2, "&");
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      String string0 = "Object must not be null";
      CharacterReader characterReader0 = new CharacterReader("Object must not be null");
      characterReader0.consumeAsString();
      char[] charArray0 = null;
      characterReader0.consume();
      // Undeclared exception!
      try { 
        characterReader0.matchesAnySorted((char[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Arrays", e);
      }
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("rKOAF@X.o1m0L?Xl97");
      characterReader0.consumeLetterSequence();
      characterReader0.containsIgnoreCase("rKOAF@X.o1m0L?Xl97");
      char char0 = '7';
      characterReader0.nextIndexOf('7');
      characterReader0.unconsume();
      characterReader0.consumeData();
      // Undeclared exception!
      try { 
        characterReader0.consumeAsString();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      char[] charArray0 = new char[6];
      charArray0[0] = 'a';
      charArray0[1] = 'o';
      charArray0[2] = '(';
      charArray0[3] = 'G';
      charArray0[4] = '@';
      CharacterReader characterReader0 = new CharacterReader("`<GD{iW$:#x*4e");
      characterReader0.nextIndexOf('G');
      CharacterReader characterReader1 = new CharacterReader("");
      characterReader1.consumeToEnd();
      charArray0[5] = 'l';
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("org.jsoup.parser.CharacterReader");
      char[] charArray0 = new char[6];
      charArray0[0] = '';
      charArray0[1] = 'a';
      charArray0[2] = '~';
      charArray0[3] = ';';
      charArray0[4] = 'S';
      charArray0[5] = 'l';
      characterReader0.mark();
      characterReader0.consumeToAny(charArray0);
      characterReader0.consumeHexSequence();
      characterReader0.consumeTo("org.jsoup.p");
      characterReader0.toString();
      characterReader0.matchesAnySorted(charArray0);
      characterReader0.matchesIgnoreCase("ju|%9'VVsJ&9[U8");
      characterReader0.nextIndexOf("rser.CharacterReader");
      characterReader0.consumeToAny(charArray0);
      characterReader0.consumeTo(';');
      characterReader0.matchesIgnoreCase("");
      characterReader0.matchesAny(charArray0);
      characterReader0.consumeData();
      characterReader0.consumeTagName();
      characterReader0.consumeDigitSequence();
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("|H");
      characterReader0.matchesLetter();
      characterReader0.consumeTagName();
      characterReader0.consumeTo('_');
      characterReader0.consumeTo("Must be true");
      characterReader0.matches('1');
      characterReader0.consumeTagName();
      characterReader0.consumeTagName();
      char[] charArray0 = new char[5];
      charArray0[0] = '_';
      characterReader0.consumeHexSequence();
      charArray0[1] = '_';
      charArray0[2] = '_';
      charArray0[3] = '{';
      char char0 = '*';
      charArray0[4] = '*';
      characterReader0.matchesAny(charArray0);
      // Undeclared exception!
      try { 
        characterReader0.consumeAsString();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("Z&L#tC:Bb");
      characterReader0.consumeHexSequence();
      characterReader0.rewindToMark();
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.pos();
      characterReader0.matchesLetter();
      characterReader0.matchConsume("");
      characterReader0.consumeDigitSequence();
      characterReader0.matches('L');
      characterReader0.matches("Z");
      characterReader0.matchesLetter();
      characterReader0.consumeHexSequence();
      characterReader0.pos();
      characterReader0.matchesDigit();
      characterReader0.consumeHexSequence();
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.mark();
      characterReader0.matchesLetter();
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("Array must not contain any null objects");
      characterReader0.consume();
      characterReader0.consumeAsString();
      characterReader0.consumeLetterThenDigitSequence();
      char[] charArray0 = new char[8];
      charArray0[0] = 'A';
      charArray0[1] = 'A';
      charArray0[2] = 'A';
      charArray0[3] = 'l';
      charArray0[4] = 'A';
      charArray0[5] = 'A';
      charArray0[6] = 'A';
      charArray0[7] = 'A';
      characterReader0.consumeToAnySorted(charArray0);
      characterReader0.consumeToEnd();
      characterReader0.consumeDigitSequence();
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("org.jsoup.parser.CharacterReader");
      characterReader0.unconsume();
      char char0 = 'o';
      // Undeclared exception!
      try { 
        characterReader0.consumeTo('o');
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.matchConsume("");
      char[] charArray0 = new char[2];
      charArray0[0] = 'A';
      characterReader0.unconsume();
      charArray0[1] = 'q';
      // Undeclared exception!
      try { 
        characterReader0.consumeToEnd();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("&y");
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.containsIgnoreCase("&y");
      characterReader0.advance();
      characterReader0.matchConsumeIgnoreCase("&y");
      characterReader0.unconsume();
      characterReader0.containsIgnoreCase("- I;N ,/SydRDj=@Q");
      characterReader0.unconsume();
      // Undeclared exception!
      try { 
        characterReader0.consumeLetterSequence();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      String string0 = "K6\\gQ2Agb$p<dhI";
      CharacterReader characterReader0 = new CharacterReader("K6gQ2Agb$p<dhI");
      String string1 = "xTdL]Vz;U]o<)zq";
      characterReader0.mark();
      // Undeclared exception!
      try { 
        characterReader0.consumeToAnySorted((char[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Arrays", e);
      }
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("GiM10W\"FNO");
      characterReader0.consumeDigitSequence();
      characterReader0.matches('g');
      characterReader0.matchesIgnoreCase("GiM10W\"FNO");
      char[] charArray0 = new char[2];
      charArray0[0] = 'g';
      charArray0[1] = 'g';
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.consumeToAnySorted(charArray0);
      characterReader0.consumeToAny(charArray0);
      characterReader0.matches("");
      characterReader0.rangeEquals(3361, 0, "INQ'>2u0E_G98:7)g");
      characterReader0.matchesIgnoreCase("1RH9)<Bm~#OkU2cAm");
      // Undeclared exception!
      try { 
        characterReader0.matches((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      String string0 = "(tFCstuj+~U~93UB";
      CharacterReader characterReader0 = new CharacterReader("(tFCstuj+~U~93UB");
      characterReader0.consumeTagName();
      characterReader0.current();
      char[] charArray0 = new char[5];
      charArray0[0] = '\uFFFF';
      charArray0[1] = '\uFFFF';
      characterReader0.rewindToMark();
      charArray0[2] = 'B';
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.mark();
      charArray0[3] = '\uFFFF';
      charArray0[4] = '\uFFFF';
      characterReader0.consumeToAny(charArray0);
      characterReader0.mark();
      characterReader0.matches('L');
      characterReader0.matchesAnySorted(charArray0);
      // Undeclared exception!
      try { 
        characterReader0.matchConsume((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("org.jsoup.parser.CharacterReader");
      characterReader0.matchesDigit();
      characterReader0.containsIgnoreCase("BsSg");
      characterReader0.consumeDigitSequence();
      // Undeclared exception!
      try { 
        characterReader0.consumeToAny((char[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.pos();
      char char0 = 'f';
      characterReader0.consume();
      char[] charArray0 = new char[0];
      // Undeclared exception!
      try { 
        characterReader0.consumeLetterSequence();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("Object must not be null");
      characterReader0.matchesLetter();
      characterReader0.consume();
      // Undeclared exception!
      try { 
        characterReader0.consumeTo("");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("String must not be empty");
      char[] charArray0 = new char[9];
      charArray0[0] = ':';
      charArray0[1] = 'i';
      charArray0[2] = 'P';
      characterReader0.unconsume();
      charArray0[3] = ' ';
      char char0 = '4';
      // Undeclared exception!
      try { 
        characterReader0.consumeToAny(charArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("_k");
      characterReader0.nextIndexOf("_k");
      characterReader0.containsIgnoreCase("BK:SU, !jkb65o>~ZB}");
      characterReader0.consumeAsString();
      // Undeclared exception!
      try { 
        characterReader0.nextIndexOf((CharSequence) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("Object must not be null");
      characterReader0.nextIndexOf("Object must not be null");
      characterReader0.advance();
      char[] charArray0 = new char[1];
      characterReader0.consumeHexSequence();
      characterReader0.advance();
      charArray0[0] = '?';
      characterReader0.matchesAnySorted(charArray0);
      characterReader0.nextIndexOf("b");
      characterReader0.consumeDigitSequence();
      char[] charArray1 = new char[0];
      characterReader0.matchesAnySorted(charArray1);
      characterReader0.matchesLetter();
      characterReader0.toString();
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("w");
      String string0 = "";
      characterReader0.rewindToMark();
      characterReader0.matchesLetter();
      characterReader0.unconsume();
      // Undeclared exception!
      try { 
        characterReader0.nextIndexOf("w");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      String string0 = "o}y]DhZPWI+\"EQM/*n.";
      CharacterReader characterReader0 = new CharacterReader("o}y]DhZPWI+\"EQM/*n.");
      characterReader0.unconsume();
      characterReader0.unconsume();
      // Undeclared exception!
      try { 
        characterReader0.consumeLetterSequence();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -2
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      String string0 = "";
      CharacterReader characterReader0 = new CharacterReader("");
      String string1 = "]cHtN'I^3VN1&P1";
      characterReader0.consumeHexSequence();
      characterReader0.unconsume();
      // Undeclared exception!
      try { 
        characterReader0.consumeTagName();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("S/jc!`?Y#'lu\r");
      characterReader0.consumeAsString();
      characterReader0.consume();
      characterReader0.matchConsume("d=X!r4>=");
      characterReader0.rewindToMark();
      characterReader0.consumeDigitSequence();
      characterReader0.consumeHexSequence();
      characterReader0.unconsume();
      characterReader0.pos();
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("Z&L#tC:Bb");
      characterReader0.consumeHexSequence();
      characterReader0.rewindToMark();
      characterReader0.consumeData();
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.pos();
      characterReader0.matchesLetter();
      characterReader0.matchConsume("Z");
      characterReader0.consumeDigitSequence();
      char[] charArray0 = new char[7];
      charArray0[0] = 'V';
      charArray0[1] = '.';
      charArray0[2] = 'd';
      charArray0[3] = '.';
      charArray0[4] = 'P';
      charArray0[5] = 'w';
      charArray0[6] = 'L';
      characterReader0.matchesAny(charArray0);
      characterReader0.matches('L');
      characterReader0.matches("");
      characterReader0.matchesLetter();
      characterReader0.consumeHexSequence();
      characterReader0.pos();
      characterReader0.matchesDigit();
      characterReader0.consumeHexSequence();
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.mark();
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("5");
      characterReader0.consumeHexSequence();
      characterReader0.consumeHexSequence();
      characterReader0.matchConsumeIgnoreCase("");
      characterReader0.matchesDigit();
      characterReader0.containsIgnoreCase("5");
      characterReader0.consumeDigitSequence();
      characterReader0.rewindToMark();
      char[] charArray0 = new char[4];
      charArray0[0] = '+';
      characterReader0.consumeTo('x');
      characterReader0.consume();
      charArray0[1] = ';';
      characterReader0.mark();
      charArray0[2] = '#';
      charArray0[3] = '6';
      characterReader0.consumeDigitSequence();
      characterReader0.matchesAnySorted(charArray0);
      characterReader0.consumeData();
      characterReader0.unconsume();
      characterReader0.matches("");
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.unconsume();
      characterReader0.matchesDigit();
      characterReader0.consumeTo('^');
      characterReader0.mark();
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      String string0 = "4KwX";
      CharacterReader characterReader0 = new CharacterReader("4KwX");
      String string1 = "";
      characterReader0.matchConsume("");
      characterReader0.matchesDigit();
      characterReader0.unconsume();
      // Undeclared exception!
      try { 
        characterReader0.matches("4KwX");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("_t6.~'");
      characterReader0.advance();
      characterReader0.matches('M');
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("m&e%BWKb_?$4cmU&");
      characterReader0.matchesDigit();
      characterReader0.unconsume();
      characterReader0.advance();
      char[] charArray0 = new char[7];
      characterReader0.consumeToAnySorted(charArray0);
      charArray0[0] = 'L';
      charArray0[1] = 'F';
      characterReader0.consumeLetterSequence();
      charArray0[2] = 'o';
      characterReader0.consumeToAnySorted(charArray0);
      charArray0[3] = '-';
      charArray0[4] = '[';
      charArray0[5] = 'A';
      charArray0[6] = '2';
      characterReader0.consumeToAnySorted(charArray0);
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader(" =5b;4Q-^FIUEfNQ#");
      char[] charArray0 = new char[4];
      charArray0[0] = '0';
      charArray0[1] = '4';
      charArray0[2] = 'd';
      characterReader0.consumeToAnySorted(charArray0);
      charArray0[3] = '=';
      characterReader0.matchConsume(",E,!d*4O4oG@~");
      characterReader0.consumeToAny(charArray0);
      characterReader0.consumeDigitSequence();
      characterReader0.current();
      characterReader0.consumeTo('Q');
      characterReader0.consumeDigitSequence();
      characterReader0.consumeData();
      characterReader0.consumeHexSequence();
      characterReader0.matchesAny(charArray0);
      characterReader0.matches(" =5b;4Q-^FIUEfNQ#");
      characterReader0.matchConsumeIgnoreCase("");
      characterReader0.advance();
      characterReader0.consumeData();
      characterReader0.consumeData();
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("@6>(8]5}2J");
      characterReader0.matchConsumeIgnoreCase("9lP}qT~7");
      characterReader0.consumeData();
      char char0 = '0';
      characterReader0.consumeTo('0');
      characterReader0.consumeLetterSequence();
      characterReader0.mark();
      characterReader0.consume();
      characterReader0.consumeTagName();
      characterReader0.current();
      characterReader0.isEmpty();
      characterReader0.matches('\uFFFF');
      characterReader0.nextIndexOf('\uFFFF');
      characterReader0.rewindToMark();
      characterReader0.consume();
      characterReader0.current();
      // Undeclared exception!
      try { 
        characterReader0.consumeTo('\uFFFF');
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("u7d5 4#u/=>9d;~");
      characterReader0.rewindToMark();
      characterReader0.unconsume();
      // Undeclared exception!
      try { 
        characterReader0.consumeDigitSequence();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("&iGo/5=mVob>c");
      characterReader0.consumeData();
      characterReader0.consumeHexSequence();
      characterReader0.matchConsume("\"@cJ~?9yD+CM14O");
      characterReader0.unconsume();
      // Undeclared exception!
      try { 
        characterReader0.consumeData();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("7/?vcl= @jLS,uX");
      char[] charArray0 = new char[2];
      charArray0[0] = 'H';
      charArray0[1] = ',';
      characterReader0.consumeToAny(charArray0);
      characterReader0.consumeTo('v');
      characterReader0.advance();
      characterReader0.matchConsumeIgnoreCase("7/?vcl= @jLS,uX");
      characterReader0.rewindToMark();
      characterReader0.consumeTo('H');
      characterReader0.matchesLetter();
      characterReader0.rewindToMark();
      characterReader0.mark();
      characterReader0.consumeHexSequence();
      characterReader0.rewindToMark();
      characterReader0.matchConsumeIgnoreCase("bT)w");
      characterReader0.consume();
      characterReader0.consume();
      characterReader0.consumeToAny(charArray0);
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("Nn@y");
      characterReader0.matches("Nn@y");
      char[] charArray0 = new char[6];
      charArray0[0] = '=';
      charArray0[1] = '+';
      charArray0[2] = '{';
      charArray0[3] = '$';
      charArray0[4] = 'Q';
      charArray0[5] = '';
      characterReader0.matchesAny(charArray0);
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader(" =5b;4Q-^FIUEfNQ#");
      char[] charArray0 = new char[4];
      charArray0[0] = '0';
      charArray0[1] = '4';
      charArray0[2] = 'd';
      charArray0[3] = '=';
      characterReader0.matchConsume(",E,!d*4O4oG@~");
      characterReader0.consumeToAny(charArray0);
      characterReader0.consumeDigitSequence();
      characterReader0.current();
      characterReader0.consumeTo('=');
      characterReader0.consumeDigitSequence();
      characterReader0.consumeData();
      characterReader0.consumeHexSequence();
      characterReader0.matchesAny(charArray0);
      characterReader0.matches(" =5b;4Q-^FIUEfNQ#");
      characterReader0.advance();
      characterReader0.consumeData();
      characterReader0.consumeData();
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      String string0 = "";
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.matchConsumeIgnoreCase("");
      characterReader0.unconsume();
      // Undeclared exception!
      try { 
        characterReader0.consume();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("'?pH<g");
      characterReader0.consumeData();
      characterReader0.consumeAsString();
      characterReader0.unconsume();
      characterReader0.consumeTagName();
      characterReader0.toString();
      characterReader0.consumeToEnd();
      char[] charArray0 = new char[1];
      charArray0[0] = '\'';
      characterReader0.consumeToAny(charArray0);
      characterReader0.consume();
      characterReader0.mark();
      characterReader0.rewindToMark();
      characterReader0.rewindToMark();
      characterReader0.mark();
      characterReader0.rewindToMark();
      characterReader0.nextIndexOf("'?pH");
      // Undeclared exception!
      try { 
        characterReader0.consumeToEnd();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("lW<]Fw}9N");
      characterReader0.consumeData();
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      String string0 = "";
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.consumeToEnd();
      characterReader0.consumeHexSequence();
      characterReader0.advance();
      characterReader0.advance();
      characterReader0.rewindToMark();
      // Undeclared exception!
      try { 
        characterReader0.matchesIgnoreCase((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.containsIgnoreCase("pB7~NRFq");
      characterReader0.unconsume();
      // Undeclared exception!
      try { 
        characterReader0.consumeTo("|h[7yAJZu^Id9M");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.advance();
      characterReader0.advance();
      characterReader0.consumeData();
      // Undeclared exception!
      try { 
        characterReader0.consumeHexSequence();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("/gL+%PE~k =Fr1");
      characterReader0.consumeTagName();
      characterReader0.consumeHexSequence();
      char[] charArray0 = new char[6];
      charArray0[0] = 'z';
      charArray0[1] = 'Y';
      charArray0[2] = 'A';
      charArray0[3] = '+';
      charArray0[4] = 'q';
      charArray0[5] = 'B';
      characterReader0.consumeToAnySorted(charArray0);
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("fsu");
      characterReader0.rangeEquals(18, 18, "QeOc>ubX=-nZW@vLR");
      characterReader0.consumeTo("q=2<KqWxzui");
      characterReader0.containsIgnoreCase("fsu");
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("'XPv4EZTlqm^`6.x <");
      characterReader0.matchConsumeIgnoreCase("'XPv4EZTlqm^`6.x <");
      characterReader0.consumeTagName();
      characterReader0.containsIgnoreCase("0'*KFGsrBe|L[}");
      characterReader0.matches('#');
      characterReader0.consumeData();
      characterReader0.nextIndexOf('#');
      char[] charArray0 = new char[1];
      characterReader0.consume();
      characterReader0.consume();
      charArray0[0] = '*';
      char[] charArray1 = new char[4];
      charArray1[0] = 'V';
      characterReader0.advance();
      characterReader0.unconsume();
      charArray1[1] = 'v';
      charArray1[2] = '#';
      charArray1[3] = '#';
      characterReader0.consumeToAnySorted(charArray1);
      characterReader0.consumeToAny(charArray0);
      characterReader0.advance();
      characterReader0.mark();
      // Undeclared exception!
      try { 
        characterReader0.consumeLetterThenDigitSequence();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      String string0 = "4KwX";
      CharacterReader characterReader0 = new CharacterReader("4KwX");
      String string1 = "";
      characterReader0.matchConsume("");
      // Undeclared exception!
      try { 
        characterReader0.matchConsumeIgnoreCase((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("a/j9iV");
      characterReader0.containsIgnoreCase("a/j9iV");
      characterReader0.pos();
      char[] charArray0 = new char[6];
      charArray0[0] = '9';
      charArray0[1] = '6';
      charArray0[2] = 'v';
      characterReader0.consumeToAny(charArray0);
      charArray0[3] = 'F';
      charArray0[4] = '|';
      charArray0[5] = 'j';
      characterReader0.consumeToAnySorted(charArray0);
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("org.jsoup.parser.CharacterReader");
      characterReader0.consumeTo('C');
      characterReader0.consumeData();
      characterReader0.containsIgnoreCase("8q/+s/sZX?ZxrpPM|");
      characterReader0.unconsume();
      characterReader0.nextIndexOf("CharacterReader");
      characterReader0.matchesIgnoreCase("");
      characterReader0.consumeTagName();
      characterReader0.matchConsume("r");
      characterReader0.matchConsume("8q/+s/sZX?ZxrpPM|");
      char[] charArray0 = new char[8];
      charArray0[0] = 'C';
      charArray0[1] = 'C';
      charArray0[2] = 'C';
      charArray0[3] = 'C';
      charArray0[4] = 'C';
      charArray0[5] = 'C';
      charArray0[6] = 'C';
      charArray0[7] = 'C';
      characterReader0.matchesAnySorted(charArray0);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.pos();
      characterReader0.consume();
      characterReader0.consumeData();
      char[] charArray0 = new char[0];
      characterReader0.consumeToAnySorted(charArray0);
      // Undeclared exception!
      try { 
        characterReader0.consumeTo('f');
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.matchesDigit();
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("*4M1'&7+%S9aW");
      characterReader0.unconsume();
      // Undeclared exception!
      try { 
        characterReader0.consumeLetterThenDigitSequence();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      String string0 = "G>";
      CharacterReader characterReader0 = new CharacterReader("G>");
      characterReader0.advance();
      characterReader0.consumeAsString();
      char[] charArray0 = new char[1];
      characterReader0.toString();
      characterReader0.consumeTo('s');
      characterReader0.consume();
      characterReader0.matchConsumeIgnoreCase("G>");
      characterReader0.unconsume();
      characterReader0.consumeDigitSequence();
      charArray0[0] = 'x';
      characterReader0.matchesAny(charArray0);
      // Undeclared exception!
      try { 
        characterReader0.nextIndexOf("");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("xVzl JCqaiSY~S");
      characterReader0.matchConsume("xVzl JCqaiSY~S");
      characterReader0.consumeLetterThenDigitSequence();
      // Undeclared exception!
      try { 
        characterReader0.consumeAsString();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("q^&|gaEE%");
      characterReader0.unconsume();
      // Undeclared exception!
      try { 
        characterReader0.consumeHexSequence();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.matchConsumeIgnoreCase("");
      characterReader0.advance();
      String string0 = "E_rtVFT=&>{";
      characterReader0.matches("E_rtVFT=&>{");
      // Undeclared exception!
      try { 
        characterReader0.consumeDigitSequence();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("aD#rw7");
      characterReader0.consumeLetterSequence();
      characterReader0.unconsume();
      characterReader0.advance();
      characterReader0.consumeAsString();
      characterReader0.matchesLetter();
      characterReader0.consumeLetterSequence();
      characterReader0.matchConsumeIgnoreCase("rw");
      characterReader0.current();
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.isEmpty();
      characterReader0.matchesIgnoreCase("#");
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.advance();
      characterReader0.matches("-_b0h`1ZT-4-");
      characterReader0.consumeTagName();
      characterReader0.consumeHexSequence();
      characterReader0.mark();
      // Undeclared exception!
      try { 
        characterReader0.consumeAsString();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("org.jsoup.parser.CharacterReader");
      characterReader0.consumeLetterSequence();
      characterReader0.mark();
      characterReader0.consumeTo('n');
      char[] charArray0 = new char[9];
      charArray0[0] = 'n';
      charArray0[1] = 'n';
      charArray0[2] = ')';
      charArray0[3] = 'n';
      charArray0[4] = 'n';
      charArray0[5] = 'n';
      charArray0[6] = 'n';
      charArray0[7] = 'n';
      charArray0[8] = 'n';
      characterReader0.consumeToAnySorted(charArray0);
      characterReader0.rewindToMark();
      characterReader0.consumeTagName();
      characterReader0.consumeTagName();
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader(" qkNGg/7E");
      char[] charArray0 = new char[4];
      charArray0[0] = 'U';
      charArray0[1] = ']';
      charArray0[2] = 'T';
      characterReader0.consumeLetterThenDigitSequence();
      charArray0[3] = 'p';
      characterReader0.matchesAnySorted(charArray0);
      characterReader0.toString();
      characterReader0.matchesDigit();
      characterReader0.consumeTagName();
      characterReader0.rewindToMark();
      characterReader0.matchConsume("");
      characterReader0.nextIndexOf(" qkNGg/7E");
      characterReader0.containsIgnoreCase("KjJ");
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      String string0 = "";
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.consume();
      int int0 = (-3954);
      int int1 = (-2769);
      characterReader0.consumeTagName();
      // Undeclared exception!
      try { 
        characterReader0.consumeTo("");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.consumeLetterSequence();
      characterReader0.consumeTo('g');
      characterReader0.consumeToEnd();
      characterReader0.matchConsume("~B(G2'OY0~zAyCTl8");
      characterReader0.advance();
      char[] charArray0 = new char[3];
      charArray0[0] = 'g';
      charArray0[1] = 'g';
      charArray0[2] = 'L';
      characterReader0.consumeToAny(charArray0);
      characterReader0.mark();
      characterReader0.matchConsume("");
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("`-&O56H-3a)]$ZBU,w");
      characterReader0.consumeTagName();
      characterReader0.toString();
      // Undeclared exception!
      try { 
        characterReader0.rangeEquals(0, 0, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("idsQgUTm}EHf,7L");
      characterReader0.consumeData();
      characterReader0.consumeTo("idsQgUTm}EHf,7L");
      characterReader0.consumeLetterThenDigitSequence();
      char[] charArray0 = new char[5];
      charArray0[0] = '&';
      characterReader0.consumeTo("oepsoBAwwe#JO0-");
      charArray0[1] = 'T';
      charArray0[2] = '';
      charArray0[3] = 'J';
      charArray0[4] = 'c';
      characterReader0.consumeToAnySorted(charArray0);
      characterReader0.isEmpty();
      characterReader0.consumeTo('l');
      characterReader0.unconsume();
      characterReader0.rewindToMark();
      characterReader0.nextIndexOf('<');
      characterReader0.rangeEquals(0, (-1), "");
      characterReader0.matchesLetter();
      characterReader0.mark();
      characterReader0.consumeData();
      characterReader0.rangeEquals((-195), 0, "");
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("vf5Mj=>|");
      characterReader0.matches("vf5Mj=>|");
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("L}1|");
      characterReader0.consumeLetterSequence();
      characterReader0.consumeHexSequence();
      characterReader0.consumeHexSequence();
      characterReader0.matchConsume("");
      characterReader0.consumeData();
      characterReader0.pos();
      characterReader0.consumeTagName();
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.consumeDigitSequence();
      // Undeclared exception!
      try { 
        characterReader0.containsIgnoreCase("");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("org.jsoup.parser.CharacterReader");
      characterReader0.consumeDigitSequence();
      characterReader0.consumeLetterSequence();
      characterReader0.matchesDigit();
      characterReader0.consumeDigitSequence();
      characterReader0.matchesIgnoreCase("");
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      char[] charArray0 = new char[1];
      characterReader0.consumeToAny(charArray0);
      charArray0[0] = ';';
      characterReader0.matchesAnySorted(charArray0);
      characterReader0.matchConsumeIgnoreCase("");
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      String string0 = "19-";
      CharacterReader characterReader0 = new CharacterReader("19-");
      characterReader0.consumeAsString();
      char[] charArray0 = new char[0];
      characterReader0.consumeToAnySorted(charArray0);
      characterReader0.consumeLetterThenDigitSequence();
      // Undeclared exception!
      try { 
        characterReader0.consumeTo("");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("ZJ*H+{*l+yYN");
      char[] charArray0 = new char[7];
      charArray0[0] = '8';
      charArray0[1] = 'V';
      charArray0[2] = 'm';
      charArray0[3] = 'L';
      charArray0[4] = 'T';
      charArray0[5] = '_';
      charArray0[6] = '{';
      characterReader0.consumeToAny(charArray0);
      characterReader0.consumeLetterSequence();
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.advance();
      char[] charArray0 = new char[4];
      charArray0[0] = 'l';
      charArray0[1] = ',';
      charArray0[2] = '_';
      charArray0[3] = 'e';
      characterReader0.matchesAny(charArray0);
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.consumeDigitSequence();
      characterReader0.consumeHexSequence();
      characterReader0.consume();
      characterReader0.matches('K');
      characterReader0.matchConsumeIgnoreCase("+[x-");
      characterReader0.nextIndexOf(',');
      characterReader0.matches("");
      characterReader0.unconsume();
      char[] charArray0 = new char[0];
      characterReader0.matchesAnySorted(charArray0);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("XQJQ[\"PJ!36");
      characterReader0.consumeData();
      characterReader0.consumeHexSequence();
      characterReader0.toString();
      characterReader0.consumeLetterSequence();
      // Undeclared exception!
      try { 
        characterReader0.consumeAsString();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("s-iu(W");
      char[] charArray0 = new char[4];
      charArray0[0] = '\\';
      charArray0[1] = 'E';
      charArray0[2] = '>';
      charArray0[3] = '*';
      characterReader0.consumeToAnySorted(charArray0);
      characterReader0.consumeData();
      characterReader0.mark();
      characterReader0.matchesLetter();
      characterReader0.consumeDigitSequence();
      characterReader0.current();
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("GiM10W\"FNO");
      characterReader0.consumeDigitSequence();
      characterReader0.matches('g');
      characterReader0.matchesIgnoreCase("GiM10W\"FNO");
      char[] charArray0 = new char[2];
      charArray0[0] = 'g';
      charArray0[1] = 'g';
      characterReader0.consumeToAny(charArray0);
      characterReader0.matches("");
      characterReader0.rangeEquals(3361, 0, "INQ'>2u0E_G98:7)g");
      characterReader0.consumeTo(']');
      // Undeclared exception!
      try { 
        characterReader0.matches((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.consumeTo("k#N@");
      characterReader0.matchConsumeIgnoreCase("");
      characterReader0.matchesLetter();
      characterReader0.consumeTo('\"');
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("org.jsoup.parser.CharacterReader");
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.consumeDigitSequence();
      characterReader0.advance();
      characterReader0.consumeData();
      characterReader0.matchConsume("org.jsoup.parser.CharacterReader");
      char char0 = 'J';
      characterReader0.consumeTo('J');
      characterReader0.pos();
      characterReader0.isEmpty();
      characterReader0.consumeToEnd();
      // Undeclared exception!
      try { 
        characterReader0.consumeAsString();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("w`Al/aOm.W|n&");
      characterReader0.consumeTagName();
      characterReader0.pos();
      characterReader0.mark();
      char[] charArray0 = new char[6];
      charArray0[0] = ',';
      charArray0[1] = 'Q';
      charArray0[2] = '!';
      charArray0[3] = '\'';
      charArray0[4] = 'k';
      charArray0[5] = 'Z';
      characterReader0.consumeToAny(charArray0);
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.consume();
      characterReader0.consume();
      characterReader0.advance();
      String string0 = "YcNkR\"8LN\\)zq2P<QAc";
      // Undeclared exception!
      try { 
        characterReader0.consumeTo('\uFFFF');
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      String string0 = "s%R4#[cdy {K";
      CharacterReader characterReader0 = new CharacterReader("s%R4#[cdy {K");
      characterReader0.containsIgnoreCase("8");
      characterReader0.consumeHexSequence();
      characterReader0.unconsume();
      String string1 = "RaKnoXXflN@E:(i";
      // Undeclared exception!
      try { 
        characterReader0.containsIgnoreCase("RaKnoXXflN@E:(i");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader(">!#?S>_?-g{");
      characterReader0.consumeToEnd();
      characterReader0.matchConsumeIgnoreCase("");
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("n/9Uh7K\"");
      characterReader0.matchesIgnoreCase("");
      characterReader0.nextIndexOf('Y');
      char[] charArray0 = new char[3];
      charArray0[0] = 'Y';
      charArray0[1] = 'Y';
      charArray0[2] = 'Y';
      characterReader0.consumeToAny(charArray0);
      characterReader0.nextIndexOf('2');
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.consumeToEnd();
      char char0 = '+';
      characterReader0.consumeTo('+');
      characterReader0.containsIgnoreCase("#/J.6b*$%c");
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.unconsume();
      // Undeclared exception!
      try { 
        characterReader0.matchesAny((char[]) null);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.consumeLetterSequence();
      characterReader0.consumeDigitSequence();
      characterReader0.consumeTagName();
      // Undeclared exception!
      try { 
        characterReader0.consumeTo("");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      String string0 = "Re";
      CharacterReader characterReader0 = new CharacterReader("Re");
      characterReader0.consumeTagName();
      characterReader0.rewindToMark();
      characterReader0.consumeDigitSequence();
      characterReader0.consumeToEnd();
      characterReader0.consumeHexSequence();
      // Undeclared exception!
      try { 
        characterReader0.containsIgnoreCase((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.matchConsume("");
      char[] charArray0 = new char[2];
      charArray0[0] = 'K';
      characterReader0.unconsume();
      charArray0[1] = '`';
      // Undeclared exception!
      try { 
        characterReader0.consumeToAnySorted(charArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("4xQ3;)y!UrMma'jc\"");
      characterReader0.matchConsume("/f.RHK!77KftBV");
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.mark();
      // Undeclared exception!
      try { 
        characterReader0.matchConsume((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("u:A[wz3;");
      char[] charArray0 = new char[3];
      charArray0[0] = 'D';
      charArray0[1] = 'e';
      charArray0[2] = 'o';
      characterReader0.matchesAny(charArray0);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("_?bN`~8=TqS-jq;");
      characterReader0.toString();
      characterReader0.consumeDigitSequence();
      characterReader0.consumeDigitSequence();
      characterReader0.mark();
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.toString();
      characterReader0.matchesLetter();
      characterReader0.unconsume();
      characterReader0.advance();
      characterReader0.rewindToMark();
      characterReader0.mark();
      characterReader0.advance();
      characterReader0.matchConsume("_?bN`~8=TqS-jq;");
      characterReader0.consumeData();
      characterReader0.matchConsume("_?bN`~8=TqS-jq;");
      characterReader0.nextIndexOf(')');
      characterReader0.rewindToMark();
      characterReader0.matchConsume("");
      characterReader0.current();
      characterReader0.nextIndexOf('I');
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("H,Qt:q?");
      characterReader0.consumeData();
      characterReader0.rewindToMark();
      characterReader0.nextIndexOf("H,Qt:q?");
      characterReader0.consumeDigitSequence();
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("?FY}");
      characterReader0.consumeTo('.');
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("fiqNdjv!GAK");
      characterReader0.containsIgnoreCase("fiqNdjv!GAK");
      int int0 = 1;
      characterReader0.toString();
      characterReader0.rewindToMark();
      characterReader0.rangeEquals(1, 2877, "");
      String string0 = null;
      // Undeclared exception!
      try { 
        characterReader0.consumeTo((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      String string0 = "";
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.consumeTo('/');
      characterReader0.consumeData();
      characterReader0.consumeLetterSequence();
      characterReader0.matchConsume("'*cyyD[KH8D");
      characterReader0.consumeTo("+)p'");
      characterReader0.mark();
      characterReader0.rewindToMark();
      characterReader0.isEmpty();
      characterReader0.advance();
      // Undeclared exception!
      try { 
        characterReader0.toString();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("a) *bB+Yl ");
      characterReader0.toString();
      characterReader0.consumeToEnd();
      characterReader0.rewindToMark();
      characterReader0.rangeEquals(32, (-542), "a) *bB+Yl ");
      characterReader0.current();
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("org.jsoup.parser.CharacterReader");
      characterReader0.matchesLetter();
      characterReader0.consumeHexSequence();
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("#Z=6Ug(");
      char[] charArray0 = new char[0];
      characterReader0.consumeToAny(charArray0);
      characterReader0.matchConsume("#Z=6Ug(");
      characterReader0.consumeToAnySorted(charArray0);
      characterReader0.consumeDigitSequence();
      characterReader0.pos();
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      String string0 = "4A}p\\ki8ad>=!]";
      CharacterReader characterReader0 = new CharacterReader("4A}pki8ad>=!]");
      characterReader0.consumeLetterThenDigitSequence();
      String string1 = null;
      characterReader0.consumeTagName();
      characterReader0.consumeLetterSequence();
      characterReader0.unconsume();
      // Undeclared exception!
      try { 
        characterReader0.containsIgnoreCase("");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("K6gQ2Agb$p<dhI");
      characterReader0.mark();
      characterReader0.matchConsume("xTdL]Vz;U]o<)zq");
      characterReader0.consumeHexSequence();
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.containsIgnoreCase("K6gQ2Agb$p<dhI");
      characterReader0.consumeDigitSequence();
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("^0AQ");
      characterReader0.consumeLetterSequence();
      characterReader0.unconsume();
      characterReader0.matchConsumeIgnoreCase("");
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("*'5gq3#*(4dBg!");
      characterReader0.containsIgnoreCase("*'5gq3#*(4dBg!");
      characterReader0.consumeTagName();
      characterReader0.matches('W');
      characterReader0.consume();
      characterReader0.unconsume();
      characterReader0.mark();
      // Undeclared exception!
      try { 
        characterReader0.consumeAsString();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("2N~uS0");
      characterReader0.mark();
      characterReader0.isEmpty();
      characterReader0.matchesIgnoreCase("2N~uS0");
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("'vn-P_;+3Wb{{w=");
      characterReader0.matches('s');
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      String string0 = null;
      CharacterReader characterReader0 = null;
      try {
        characterReader0 = new CharacterReader((String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Object must not be null
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.consumeToEnd();
      characterReader0.toString();
      characterReader0.nextIndexOf('r');
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader(":n&1$");
      characterReader0.matchConsume("");
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.matches("");
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("3zEJU/H");
      characterReader0.mark();
      characterReader0.consumeToEnd();
      characterReader0.consumeLetterSequence();
      characterReader0.advance();
      // Undeclared exception!
      try { 
        characterReader0.consumeAsString();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      String string0 = "02aN'[H$|jjAP ";
      CharacterReader characterReader0 = new CharacterReader("02aN'[H$|jjAP ");
      characterReader0.unconsume();
      // Undeclared exception!
      try { 
        characterReader0.consumeToEnd();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      int int0 = (-209);
      // Undeclared exception!
      try { 
        characterReader0.consumeAsString();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("XSihvv{%1IKYMQM1");
      characterReader0.mark();
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("org.jsoup.parser.CharacterReader");
      characterReader0.consume();
      characterReader0.consumeData();
  }

  @Test(timeout = 4000)
  public void test119()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("org.jsoup.parser.CharacterReader");
      characterReader0.containsIgnoreCase("org.jsoup.parser.CharacterReader");
      characterReader0.consumeData();
      characterReader0.containsIgnoreCase("PA");
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.rewindToMark();
      // Undeclared exception!
      try { 
        characterReader0.consumeTo((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test120()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("Z&L#tC:Bb");
      characterReader0.consumeHexSequence();
      characterReader0.rewindToMark();
      characterReader0.consumeData();
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.pos();
      characterReader0.matchesLetter();
      characterReader0.matchConsume("Z");
      characterReader0.consumeDigitSequence();
      char[] charArray0 = new char[7];
      charArray0[0] = 'V';
      charArray0[1] = 'V';
      charArray0[2] = 'd';
      charArray0[3] = '.';
      charArray0[4] = 'P';
      charArray0[5] = 'w';
      charArray0[6] = 'L';
      characterReader0.matchesAny(charArray0);
      characterReader0.consumeToAny(charArray0);
      characterReader0.matches('L');
      characterReader0.matches("");
      characterReader0.matchesLetter();
      characterReader0.consumeHexSequence();
      characterReader0.pos();
      characterReader0.matchesDigit();
      characterReader0.consumeHexSequence();
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.mark();
      characterReader0.consumeToEnd();
  }

  @Test(timeout = 4000)
  public void test121()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("String must not be empty");
      characterReader0.consumeTagName();
      characterReader0.consumeAsString();
      char char0 = ' ';
      characterReader0.consumeTo(' ');
      characterReader0.toString();
      characterReader0.consumeToEnd();
      characterReader0.consumeData();
      characterReader0.consumeDigitSequence();
      // Undeclared exception!
      try { 
        characterReader0.consumeAsString();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test122()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("yx;)5{EF");
      char[] charArray0 = new char[8];
      charArray0[0] = 'R';
      charArray0[1] = 'Y';
      charArray0[2] = 'y';
      charArray0[3] = ' ';
      charArray0[4] = 'T';
      characterReader0.mark();
      charArray0[5] = 'B';
      charArray0[6] = 'I';
      charArray0[7] = 'D';
      characterReader0.matchesAny(charArray0);
      characterReader0.consumeTagName();
      characterReader0.matchesIgnoreCase("yx;)5{EF");
  }

  @Test(timeout = 4000)
  public void test123()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("yr./-=P{32/ F<w");
      characterReader0.rewindToMark();
      characterReader0.toString();
      characterReader0.rewindToMark();
      characterReader0.consumeToEnd();
      char[] charArray0 = new char[7];
      charArray0[0] = 'P';
      charArray0[1] = '';
      charArray0[2] = 'N';
      charArray0[3] = '9';
      charArray0[4] = 'N';
      charArray0[5] = 'P';
      charArray0[6] = '\"';
      characterReader0.consumeToAny(charArray0);
      characterReader0.consumeHexSequence();
      characterReader0.matchConsumeIgnoreCase("yr./-=P{32/ F<w");
      characterReader0.toString();
      characterReader0.consumeTo("yr./-=P{32/ F<w");
      characterReader0.consumeTagName();
      characterReader0.matchConsume("8FOqI<WRn*");
      characterReader0.matchesLetter();
      characterReader0.consumeTagName();
      characterReader0.consumeToEnd();
      characterReader0.consumeData();
      characterReader0.consumeTo("S`u<>Y#=m");
      characterReader0.consumeHexSequence();
      characterReader0.matchesDigit();
      char[] charArray1 = new char[4];
      charArray1[0] = '_';
      charArray1[1] = '_';
      characterReader0.consumeData();
      charArray1[2] = '-';
      charArray1[3] = '4';
      characterReader0.matchesAny(charArray1);
      characterReader0.toString();
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.consumeToEnd();
      characterReader0.consumeTo('_');
  }

  @Test(timeout = 4000)
  public void test124()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("org.jsoup.parser.CharacterReader");
      characterReader0.consumeTo("org.jsoup.parser.CharacterReader");
      characterReader0.matchConsumeIgnoreCase("0m$}Qmd");
      characterReader0.matchConsume("org.jsoup.parser.CharacterReader");
      characterReader0.consumeHexSequence();
      characterReader0.advance();
      characterReader0.consumeHexSequence();
      characterReader0.consumeDigitSequence();
      characterReader0.consume();
      characterReader0.consumeTagName();
      characterReader0.consumeHexSequence();
      characterReader0.consumeData();
      characterReader0.consumeLetterThenDigitSequence();
  }

  @Test(timeout = 4000)
  public void test125()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader(">X2");
      char[] charArray0 = new char[6];
      charArray0[0] = ';';
      charArray0[1] = '}';
      charArray0[2] = '^';
      characterReader0.matchConsume("(._j^t[[lvI");
      charArray0[3] = '1';
      charArray0[4] = 'Q';
      characterReader0.consumeDigitSequence();
      charArray0[5] = '_';
      characterReader0.matchesAnySorted(charArray0);
      characterReader0.consumeTagName();
      characterReader0.matchesDigit();
  }

  @Test(timeout = 4000)
  public void test126()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("Y6s'8Byd6j#;l\"wE]");
      characterReader0.consume();
      characterReader0.consumeDigitSequence();
      char[] charArray0 = new char[7];
      characterReader0.consume();
      charArray0[0] = 'Y';
      characterReader0.unconsume();
      charArray0[1] = 'Y';
      charArray0[2] = 'Y';
      characterReader0.consumeToAnySorted(charArray0);
      charArray0[3] = 'Y';
      characterReader0.unconsume();
      characterReader0.consumeLetterThenDigitSequence();
      charArray0[4] = 'Y';
      charArray0[5] = 'Y';
      charArray0[6] = 'Y';
      characterReader0.rewindToMark();
      characterReader0.consumeToAny(charArray0);
      characterReader0.matchesIgnoreCase("");
      char char0 = 'M';
      characterReader0.nextIndexOf('M');
      characterReader0.consumeToAny(charArray0);
      char char1 = '%';
      characterReader0.mark();
      characterReader0.nextIndexOf('%');
      // Undeclared exception!
      try { 
        characterReader0.containsIgnoreCase("");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test127()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("rKOAF@X.o1m0L?Xl97");
      characterReader0.consumeTagName();
      characterReader0.consumeLetterSequence();
      characterReader0.containsIgnoreCase("rKOAF@X.o1m0L?Xl97");
      char char0 = '7';
      characterReader0.nextIndexOf('7');
      characterReader0.unconsume();
      characterReader0.consumeData();
      // Undeclared exception!
      try { 
        characterReader0.consumeAsString();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test128()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("Must be false");
      characterReader0.matchConsumeIgnoreCase("Must be false");
      characterReader0.consumeToEnd();
      characterReader0.consume();
      // Undeclared exception!
      try { 
        characterReader0.toString();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test129()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      char[] charArray0 = new char[6];
      characterReader0.consumeLetterSequence();
      charArray0[0] = 'T';
      charArray0[1] = '&';
      characterReader0.consumeData();
      charArray0[2] = 'z';
      characterReader0.matchConsume("");
      charArray0[3] = 'n';
      characterReader0.consume();
      charArray0[4] = '+';
      charArray0[5] = '-';
      characterReader0.consumeToAnySorted(charArray0);
      characterReader0.matches('T');
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.consumeDigitSequence();
  }

  @Test(timeout = 4000)
  public void test130()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("@6>(8]5}2J");
      characterReader0.matchConsumeIgnoreCase("9lP}qT~7");
      characterReader0.consumeData();
      characterReader0.mark();
      characterReader0.consume();
      characterReader0.consumeTagName();
      characterReader0.current();
      characterReader0.isEmpty();
      characterReader0.matches('\uFFFF');
      characterReader0.nextIndexOf('\uFFFF');
      characterReader0.rewindToMark();
      characterReader0.consume();
      characterReader0.current();
      // Undeclared exception!
      try { 
        characterReader0.consumeTo('\uFFFF');
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test131()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("}qiLutw$<9QNY1pZds");
      characterReader0.advance();
      characterReader0.matchConsumeIgnoreCase("");
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.consumeHexSequence();
      characterReader0.containsIgnoreCase("}qiLutw$<9QNY1pZds");
      char[] charArray0 = new char[6];
      charArray0[0] = 'a';
      char char0 = 'o';
      // Undeclared exception!
      try { 
        characterReader0.consumeToAny((char[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.parser.CharacterReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test132()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("&u6K3,PhAgv+4%E");
      characterReader0.consumeTagName();
      char[] charArray0 = new char[8];
      charArray0[0] = '^';
      characterReader0.unconsume();
      charArray0[1] = 'L';
      charArray0[2] = '9';
      characterReader0.consumeToAny(charArray0);
      charArray0[3] = 'j';
      charArray0[4] = '^';
      charArray0[5] = '(';
      charArray0[6] = 't';
      charArray0[7] = 'U';
      characterReader0.consumeToAny(charArray0);
      characterReader0.matchesIgnoreCase("&u6K3,PhAgv+4%E");
      characterReader0.matches('+');
      characterReader0.matches('^');
  }

  @Test(timeout = 4000)
  public void test133()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("d");
      characterReader0.matchesDigit();
      characterReader0.nextIndexOf('h');
      characterReader0.consumeHexSequence();
      char[] charArray0 = new char[9];
      characterReader0.consumeToAny(charArray0);
      charArray0[0] = 'l';
      charArray0[1] = 'u';
      charArray0[2] = 'l';
      charArray0[3] = 'V';
      charArray0[4] = '9';
      charArray0[5] = '9';
      charArray0[6] = '+';
      charArray0[7] = ' ';
      charArray0[8] = 'n';
      characterReader0.matchesAnySorted(charArray0);
  }

  @Test(timeout = 4000)
  public void test134()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("if!0");
      char[] charArray0 = new char[7];
      charArray0[0] = 'I';
      characterReader0.toString();
      characterReader0.consumeLetterSequence();
      charArray0[2] = '9';
      charArray0[3] = '=';
      charArray0[4] = 'j';
      charArray0[5] = '$';
      charArray0[6] = 'h';
      characterReader0.consume();
      characterReader0.consumeToAnySorted(charArray0);
      characterReader0.matchesIgnoreCase("0");
      characterReader0.consumeData();
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.consumeDigitSequence();
      characterReader0.consumeDigitSequence();
      characterReader0.matchesIgnoreCase("");
      characterReader0.consumeToAnySorted(charArray0);
      characterReader0.matches('I');
      characterReader0.matches("");
      characterReader0.matchesDigit();
      characterReader0.consumeToAnySorted(charArray0);
      characterReader0.matches("K3/kPoYs");
      characterReader0.consumeTagName();
  }

  @Test(timeout = 4000)
  public void test135()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("String must not be empty");
      characterReader0.consumeToEnd();
      characterReader0.toString();
      char[] charArray0 = new char[7];
      charArray0[0] = '9';
      charArray0[1] = '9';
      characterReader0.mark();
      charArray0[2] = 'k';
      charArray0[3] = 'q';
      characterReader0.consumeTo('u');
      charArray0[4] = '~';
      charArray0[5] = '<';
      charArray0[6] = '~';
      characterReader0.matchesAnySorted(charArray0);
      characterReader0.matchesLetter();
      String string0 = "";
      // Undeclared exception!
      try { 
        characterReader0.consumeTo("");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test136()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("Strinomust not be empty");
      characterReader0.consumeToEnd();
      characterReader0.rewindToMark();
      characterReader0.toString();
      char[] charArray0 = new char[7];
      charArray0[0] = '9';
      charArray0[1] = '9';
      characterReader0.mark();
      charArray0[2] = 'k';
      charArray0[3] = 'q';
      characterReader0.consumeTo('u');
      charArray0[4] = '~';
      charArray0[5] = '<';
      charArray0[6] = 'u';
      characterReader0.matchesAnySorted(charArray0);
      characterReader0.matchesLetter();
      characterReader0.consumeToAnySorted(charArray0);
      String string0 = "";
      characterReader0.matchesAnySorted(charArray0);
      // Undeclared exception!
      try { 
        characterReader0.consumeTo("");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test137()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("Z&L#tC:Bb");
      characterReader0.consumeHexSequence();
      characterReader0.rewindToMark();
      characterReader0.consumeData();
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.pos();
      characterReader0.matchesLetter();
      characterReader0.matchConsume("Z");
      characterReader0.consumeDigitSequence();
      char[] charArray0 = new char[7];
      charArray0[1] = '\u0000';
      charArray0[3] = '.';
      charArray0[5] = 'w';
      charArray0[6] = 'L';
      characterReader0.matchesAny(charArray0);
      characterReader0.matches('L');
      characterReader0.toString();
      characterReader0.matches("");
      characterReader0.matchesLetter();
      characterReader0.consumeHexSequence();
      characterReader0.pos();
      characterReader0.matchesDigit();
      characterReader0.consumeHexSequence();
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.mark();
      CharBuffer charBuffer0 = CharBuffer.wrap((CharSequence) "");
      // Undeclared exception!
      try { 
        characterReader0.nextIndexOf(charBuffer0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test138()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("D");
      characterReader0.consumeHexSequence();
      characterReader0.unconsume();
      char[] charArray0 = new char[6];
      characterReader0.consumeHexSequence();
      charArray0[0] = '\'';
      characterReader0.consumeTo("D");
      charArray0[1] = '#';
      charArray0[2] = 'Q';
      charArray0[3] = ':';
      charArray0[4] = '\'';
      charArray0[5] = '\'';
      characterReader0.rewindToMark();
      characterReader0.consumeToAnySorted(charArray0);
      characterReader0.consumeTagName();
      characterReader0.rewindToMark();
      characterReader0.consumeTo("D");
      characterReader0.consumeTo('l');
      characterReader0.advance();
      characterReader0.advance();
      characterReader0.current();
      characterReader0.consumeData();
      characterReader0.isEmpty();
      // Undeclared exception!
      try { 
        characterReader0.toString();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test139()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("H,Qt:+|q?");
      characterReader0.rewindToMark();
      characterReader0.consumeData();
      characterReader0.rewindToMark();
      characterReader0.nextIndexOf("H,Qt:+|q?");
      characterReader0.consumeDigitSequence();
      characterReader0.consumeTagName();
      // Undeclared exception!
      try { 
        characterReader0.consumeTo("");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test140()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("org.jsoup.parser.CharacterReader");
      characterReader0.consumeTo('o');
      characterReader0.toString();
      characterReader0.consumeAsString();
      characterReader0.rewindToMark();
      characterReader0.advance();
      char[] charArray0 = new char[4];
      charArray0[2] = 'o';
      characterReader0.consumeToAny(charArray0);
      characterReader0.consumeTo("org.jsoup.parser.CharacterReader");
      characterReader0.matchConsume("org.jsoup.parser.CharacterReader");
      characterReader0.toString();
      char[] charArray1 = new char[7];
      charArray1[1] = 'o';
      charArray1[4] = 'M';
      charArray1[6] = 'o';
      characterReader0.consumeToAny(charArray1);
  }

  @Test(timeout = 4000)
  public void test141()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("pR=b$!Qu;t0'JW");
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.consume();
      characterReader0.containsIgnoreCase("pR=b$!Qu;t0'JW");
      characterReader0.matchesLetter();
      characterReader0.matches("pR");
      characterReader0.matchConsumeIgnoreCase("pR=b$!Qu;t0'JW");
      characterReader0.unconsume();
      characterReader0.containsIgnoreCase("- I;N ,/SydRDj=@Q");
      characterReader0.unconsume();
      characterReader0.consumeLetterSequence();
      characterReader0.consumeTo("pR");
      characterReader0.unconsume();
      // Undeclared exception!
      try { 
        characterReader0.containsIgnoreCase("");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test142()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("px8*+g");
      characterReader0.consumeLetterThenDigitSequence();
      char[] charArray0 = new char[3];
      charArray0[0] = 'P';
      charArray0[1] = 'P';
      characterReader0.consume();
      characterReader0.consumeData();
      characterReader0.consumeDigitSequence();
      charArray0[1] = 'I';
      characterReader0.unconsume();
      characterReader0.matchConsume("+g");
      characterReader0.consumeToAny(charArray0);
      characterReader0.consume();
      characterReader0.unconsume();
      characterReader0.advance();
      characterReader0.consume();
      characterReader0.matchConsume("");
      characterReader0.unconsume();
      // Undeclared exception!
      try { 
        characterReader0.consumeToEnd();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }
}
